version: "3.10"

services:
  flask_app:
    build: ./flask_app
    privileged: true
    restart: always
    volumes:
      - ./flask_app:/app
    env_file:
      - ./.envs/.env
      - ./.envs/.env.db
    ports:
      - 5000:8000
    depends_on:
      - db
    networks:
      - evraz

  kafka_consumer:
    build: ./kafka_consumer
    privileged: true
    restart: always
    volumes:
      - ./kafka_consumer:/app
    env_file:
      - ./.envs/.env
      - ./.envs/.env.db
    #    ports:
    #      - 8000:8000
    depends_on:
      - db
    networks:
      - evraz

  # TODO: add healthcheck
  db:
    container_name: db
    image: postgres:14.5
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:rw
    env_file:
      - ./.envs/.env.db
    networks:
      - evraz

networks:
  evraz:
    driver: bridge
